# backend/Dockerfile
FROM node:22-alpine

WORKDIR /app

# Instala pnpm con corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./

RUN pnpm install --prod

COPY . .

EXPOSE 3000

CMD ["pnpm", "start"]
